#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-QUIC
Version  : 1.1
Release  : 1
URL      : https://cran.r-project.org/src/contrib/QUIC_1.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/QUIC_1.1.tar.gz
Summary  : Regularized sparse inverse covariance matrix estimation
Group    : Development/Tools
License  : GPL-3.0
Requires: R-QUIC-lib = %{version}-%{release}
BuildRequires : buildreq-R

%description
regularized inverse covariance matrix estimation problem.

%package lib
Summary: lib components for the R-QUIC package.
Group: Libraries

%description lib
lib components for the R-QUIC package.


%prep
%setup -q -c -n QUIC

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1584112865

%install
export SOURCE_DATE_EPOCH=1584112865
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library QUIC
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library QUIC
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library QUIC
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc QUIC || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/QUIC/CITATION
/usr/lib64/R/library/QUIC/DESCRIPTION
/usr/lib64/R/library/QUIC/INDEX
/usr/lib64/R/library/QUIC/Meta/Rd.rds
/usr/lib64/R/library/QUIC/Meta/data.rds
/usr/lib64/R/library/QUIC/Meta/demo.rds
/usr/lib64/R/library/QUIC/Meta/features.rds
/usr/lib64/R/library/QUIC/Meta/hsearch.rds
/usr/lib64/R/library/QUIC/Meta/links.rds
/usr/lib64/R/library/QUIC/Meta/nsInfo.rds
/usr/lib64/R/library/QUIC/Meta/package.rds
/usr/lib64/R/library/QUIC/NAMESPACE
/usr/lib64/R/library/QUIC/R/QUIC
/usr/lib64/R/library/QUIC/R/QUIC.rdb
/usr/lib64/R/library/QUIC/R/QUIC.rdx
/usr/lib64/R/library/QUIC/data/ER_692.RData
/usr/lib64/R/library/QUIC/data/datalist
/usr/lib64/R/library/QUIC/demo/ER.R
/usr/lib64/R/library/QUIC/demo/ERpath.R
/usr/lib64/R/library/QUIC/help/AnIndex
/usr/lib64/R/library/QUIC/help/QUIC.rdb
/usr/lib64/R/library/QUIC/help/QUIC.rdx
/usr/lib64/R/library/QUIC/help/aliases.rds
/usr/lib64/R/library/QUIC/help/paths.rds
/usr/lib64/R/library/QUIC/html/00Index.html
/usr/lib64/R/library/QUIC/html/R.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/QUIC/libs/QUIC.so
/usr/lib64/R/library/QUIC/libs/QUIC.so.avx2
/usr/lib64/R/library/QUIC/libs/QUIC.so.avx512
